-module(problem002).
-export([solve/0]).

%%%%
% Each new term in the Fibonacci sequence is generated by adding the previous two terms.
% By starting with 1 and 2, the first 10 terms will be:
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% By considering the terms in the Fibonacci sequence whose values do not exceed four million,
% find the sum of the even-valued terms.
%%%%

%% solution = 4613732

solve() ->
  lists:sum(lists:filter(fun(X) -> even(X) end, fib_max(4000000))).

even(X) ->
  (X rem 2 == 0).

% Returns the Fibonnaci sequence until Max
fib_max(Max) ->
  fib_max(Max, 0, 1, []).
fib_max(Max, Current, _,  Sequence) when Current > Max ->
  lists:reverse(Sequence);
fib_max(Max, Current, Next, Sequence) ->
  fib_max(Max, Next, Current + Next, [Current|Sequence]).